openapi: 3.0.1
info:
  title: '@jupiterone/graph-okta'
  description: A JupiterOne Integration for https://www.okta.com
  x-cortex-git:
    github:
      repository: JupiterOne/graph-okta
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-okta'
